name: Force Bump PR

on:
  workflow_dispatch:

jobs:
  call-build-workflow:
    uses: dprince/openstack-k8s-operators-ci/.github/workflows/force-bump-pull-request.yaml@force-bump-pull-request
    with:
      operator_name: keystone
      branch_name: ${{ github.ref_name }}
